# config/default.toml
# Intended for regular use: can be modified, also through Python. 
[parallelization_parameters]
number_threads = 1
simulations_per_thread = 1

[simulation_parameters]
# Neutron settings
neutron_initial_position = { x = 0.05, y = 0.3, z = -0.5 }
neutron_generation_cap = 100                    # Maximum number of generations: simulated will be halted. 
neutron_count_cap = 5000                        # Maximum number of neutrons: simulated will be halted unless enforce_maximum_neutron_count is true. 
initial_neutron_count = 1000                    # Initial number of neutrons. 
maximum_neutron_energy_difference = 0.01        # Maximum energy difference from elastic collisions before the material properties are updated. 
enforce_maximum_neutron_count = true            # Removes any neutrons beyond neutron_count_cap. Useful for power estimation. 
halt_time = 1e-5                                # Removes any neutron after this time. Useful for power estimation. 
track_from_generation = 5                       # Generation from which to start tracking results. Reduces initialization bias. 

# Geometries 
geometries_path = 'config/geometries/working_reactor.toml'

# Diagnostics
track_creation = true                           # Tracks creation of neutrons per generation. Required for k-estimation. 
track_positions = false                         # Track all neutron positions. 
track_energies = false                          # Track neutron energies. 
track_bins = true                               # Tracks presence and fission events. Required for tracking total number of fission events. 
plot_geometry = false                           # Plotting the geometry in a format that ParaView can load in as a CSV. 
write_results = true                            # Calculates everything but does not write any results to diagnostics file except the simulation report if set to false. 

# Post-processing
model_heat_diffusion = false                    # Simulating heat diffusion using the calculated bins. 

[heat_diffusion_parameters]
source_data_file = 'path/to/source/'
neutron_multiplier = 5.5e4                      # Neutron multiplier for the heat diffusion. 
convective_heat_transfer_coefficient = 14349    # Based on Nusselt for a flat plate, spacing of 1.5 cm. 
thermal_conductivity = 27.0                     # Thermal conductivity. 
density = 17300.0                               # Density. 
heat_capacity = 116.0                           # Heat capacity. 
external_temperature = 293.15                   # External temperature applied to the plates. 
time_step = 0.01                                # Time step in the heat diffusion model. 
t_end = 50.0                                    # Simulation time (s).
write_interval = 100                            # Iterations. 


[bin_parameters]
center = { x = 0.05, y = 0.3, z = -0.5 }
length_count = 7
depth_count = 40
height_count = 40
total_length = 0.07
total_depth = 0.40
total_height = 0.40

[plot_parameters]
center = { x = 0.0, y = 0.0, z = 0.0 }
length_count = 100
depth_count = 100
height_count = 100
total_length = 2
total_depth = 2
total_height = 4