# config/reference.toml
# This TOML is loaded by the test simulations to ensure the code is working as expected. 
# The parameters in here should not be modified without prior testing and validation, otherwise the tests may become unreliable. 
# The bin parameters are not actually used, but are left in, in case we want to do further validation later on. 

[parallelization_parameters]
number_threads = 1
simulations_per_thread = 1

[simulation_parameters]
run_name = 'Reference run'
neutron_generation_cap = 200
neutron_count_cap = 100000
initial_neutron_count = 100
variance_reduction = false
specified_neutron_count = 10000
neutron_fission_count_cap = 100000000
estimate_k = true
track_fission_positions = false 
track_bins = false
plot_geometry = false 
maximum_neutron_energy_difference = 0.01 
geometries_path = ""
neutron_initial_position = { x = 0.0, y = 0.0, z = 0.0 }
track_from_generation = 5 # Generation from which to start tracking results. 
model_heat_diffusion = false 
neutron_multiplier = 0
calculate_convergence = false                          # Enabling convergence analysis. 
convergence_analysis_period = 1                       # Check convergence per this number of generations. 
minimum_convergence_level = 1e-5                      # Halting criterion for convergence. 

[heat_diffusion_parameters]
source_data_file = '/path/to/source/result'
minimum_relevant_property_index = 4 # Minimum property index: anything less than this is considered a boundary condition. 
neutron_multiplier = 5.5e4 # Neutron multiplier for the heat diffusion. 
convective_heat_transfer_coefficient = 14349 # Based on Nusselt for a flat plate, spacing of 1.5 cm. 
initial_internal_temperature = 600.0 # Initial material temperature. 
external_temperature = 293.15 # External temperature applied to the plates. 
t_delta = 0.01 # Time step in the heat diffusion model. 
t_end = 50.0 # Simulation time (s).
write_interval = 100 # Iterations. 
save_files = true # Saving heat diffusion CSVs. 

[neutron_bins]
length_count = 200
depth_count = 200
height_count = 200
total_length = 2.0
total_depth = 2.0
total_height = 2.0
center = { x = 0.0, y = 0.0, z = 0.0 }

[geometry_plot_bins]
center = { x = 0.0, y = 0.0, z = 0.0 }
length_count = 200
depth_count = 200
height_count = 200
total_length = 2.0
total_depth = 2.0
total_height = 2.0

[heat_diffusion_bins]
center = { x = 0.0, y = 0.0, z = 0.0 }
length_count = 100
depth_count = 100
height_count = 100
total_length = 2
total_depth = 2
total_height = 4